/* eslint-disable */
/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9afb12c9e579806297cdda381de9f090)
export interface __BaseEnv_Env {
  SIGNAGE_MEDIA: R2Bucket
  DB: D1Database
  ASSETS: Fetcher
}
export interface Env extends __BaseEnv_Env {}

declare global {
  namespace Cloudflare {
    interface GlobalProps {
      mainModule: typeof import('./worker/index')
    }
    interface Env extends __BaseEnv_Env {}
  }
}
